In [93]:
import nbformat as nbf

In [94]:
nb_id = "airbnb/airbnb"
nb = nbf.read(f"{nb_id}.ipynb",as_version=4) #the toy original is the pandas-only control
code = "import lux"
nb["cells"].insert(0,nbf.v4.new_code_cell(code))
nbf.write(nb, f'{nb_id}_baseline.ipynb')

In [95]:
nb = nbf.read(f"{nb_id}.ipynb",as_version=4) 
code = "import lux\nlux.config.lazy_maintain = True"
nb["cells"].insert(0,nbf.v4.new_code_cell(code))
nbf.write(nb, f'{nb_id}_o1.ipynb')

In [96]:
nb = nbf.read(f"{nb_id}.ipynb",as_version=4) 
code = "import lux\nlux.config.lazy_maintain = True\nlux.config.early_pruning = True"
nb["cells"].insert(0,nbf.v4.new_code_cell(code))
nbf.write(nb, f'{nb_id}_o1o2.ipynb')

In [97]:
nb = nbf.read(f"{nb_id}.ipynb",as_version=4) 
code = "import lux\nlux.config.lazy_maintain = True\nlux.config.early_pruning = True\nlux.config.streaming = True"
nb["cells"].insert(0,nbf.v4.new_code_cell(code))
nbf.write(nb, f'{nb_id}_o1o2o3.ipynb')

------------------------------------------------------------------------------------------

In [111]:
import glob
import time
import papermill as pm
import pandas as pd
import numpy as np
import json
trial = []

for nb_name in glob.glob("airbnb/airbnb_*_*_output.ipynb"):
# for nb_name in glob.glob("airbnb/airbnb_*_*_output.ipynb"):
    _, condition, nPts, _ = nb_name.split("_")
    with open(nb_name) as json_file:
        data = json.load(json_file)
        for cell in data['cells']:
            label = cell["source"][0]
            if "# {{NO LUX}}" in label:
                cell_type = "python"
            elif "# {{PRINT SERIES}}" in label:
                cell_type = "print_series"
            elif "# {{PRINT DF}}" in label:
                cell_type = "print_dataframe"
            duration = cell["metadata"]["papermill"]["duration"]
#             print(nb_name, cell_type, duration)
            trial.append([condition, nPts,cell_type, duration])

In [113]:
trial = pd.DataFrame(trial,columns=["condition","nPts","cell_type","time"])

In [114]:
trial.groupby("cell_type").count()

condition  nPts  time
cell_type                             
print_dataframe        196   196   177
print_series            98    98    88
python                 294   294   274

--------------

In [121]:
import pandas as pd
import altair as alt

In [125]:
overall = trial.groupby("condition").sum().reset_index()

In [126]:
overall

condition         time
0  baseline  1699.424212
1        o1   266.640720
2      o1o2   167.146463
3    o1o2o3   127.370984

In [128]:
alt.Chart(overall).mark_bar().encode(
    x = "condition",
    y = alt.Y("time",scale=alt.Scale(type='log'),title="log(total time)"),
)

alt.Chart(...)

In [6]:
df = pd.read_csv("macrobenchmark.csv")

In [7]:
df.nPts = df.nPts.astype(int)

In [8]:
df["condition"] = df.nb_name.replace({"toy_o1.ipynb":"o1",
                    "toy_o1o2o3.ipynb":"o1o2o3",
                    "toy_o1o2.ipynb":"o1o2",
                    "toy.ipynb":"pandas",
                    "toy_baseline.ipynb":"no opt"})

In [9]:
alt.Chart(df).mark_bar().encode(
    x = "condition",
    y = alt.Y("time",scale=alt.Scale(type='log'),title="log(total time)"),
    column="nPts",
    color="condition"
)

alt.Chart(...)

In [10]:
# # VegaLite can not do logarithmic stacked bar since it is misleading
# alt.Chart(df).mark_bar().encode(
#     x = alt.X("nPts",type="ordinal"),
#     y = alt.Y("time"),#,scale=alt.Scale(type='log'),title="log(total time)"),
#     color="condition"
# )

In [26]:
df = df.drop(columns="nb_name")

In [53]:
pdonly = df[df["condition"]=="pandas"]
best = df[df["condition"]=="o1o2o3"]
worst = df[df["condition"]=="no opt"]

In [ ]:
import numpy as np

In [68]:
def pctChange(s1,s2):
    return (np.array(s1["time"])-np.array(s2["time"]))/np.array(s2["time"])

In [69]:
best["time"]

3      33.051949
8      24.736191
13     42.343533
18    197.560367
Name: time, dtype: float64

In [70]:
pctChange(best,pdonly)

array([0.52858007, 0.16597767, 0.74957558, 2.80147911])

In [71]:
pctChange(worst,pdonly)

array([ 3.77364417,  4.78507636, 15.92258916, 53.6757692 ])

In [73]:
pctChange(worst,best)

array([ 2.12292714,  3.96156705,  8.67239677, 13.38276199])