In [1]:
cd ../backend/macrobenchmark/

/Users/dorislee/Desktop/Research/lux/lux-benchmark/backend/macrobenchmark


In [32]:
import glob
import time
import papermill as pm
import pandas as pd
import numpy as np
import json
count = []
with open("airbnb/airbnb.ipynb") as json_file:
    data = json.load(json_file)
    for cell in data['cells']:
        label = cell["source"][0]
        cell_type = None
        if "# {{NO LUX}}" in label:
            cell_type = "python"
        elif "# {{PRINT SERIES}}" in label:
            cell_type = "print_series"
        elif "# {{PRINT DF}}" in label:
            cell_type = "print_dataframe"
        count.append(cell_type)
count = pd.Series(count)
print(count.value_counts())

python             17
print_dataframe    14
print_series        7
dtype: int64


In [33]:
trial = []

for nb_name in glob.glob("airbnb/airbnb_*_output.ipynb"):
# for nb_name in glob.glob("airbnb/airbnb_*_*_output.ipynb"):
    snb = nb_name.split("_")
    if len(snb)==4:
        _, condition, nPts, _ = nb_name.split("_")
    elif len(snb)==3:
        condition = "pandas"
        _,  nPts, _ = nb_name.split("_")
    with open(nb_name) as json_file:
        data = json.load(json_file)
        for cell in data['cells']:
            label = cell["source"][0]
            cell_type = None
            if "# {{NO LUX}}" in label:
                cell_type = "python"
            elif "# {{PRINT SERIES}}" in label:
                cell_type = "print_series"
            elif "# {{PRINT DF}}" in label:
                cell_type = "print_dataframe"
            duration = cell["metadata"]["papermill"]["duration"]
#             print(nb_name, cell_type, duration)
            trial.append([condition, nPts,cell_type, duration])

In [34]:
trial = pd.DataFrame(trial,columns=["condition","nPts","cell_type","time"])

In [35]:
trial.to_csv("../../paper/airbnb_macrobenchmark.csv",index=None)

In [5]:
# trial.groupby("cell_type").count()

--------------

In [6]:
import pandas as pd
import altair as alt

In [7]:
overall = trial.groupby("condition").sum().reset_index()

In [8]:
overall

condition         time
0  baseline  8651.522527
1        o1  1179.947828
2      o1o2   711.051617
3    o1o2o3   568.308264
4    pandas   172.361008

In [9]:
alt.Chart(overall).mark_bar().encode(
    x = "condition",
    y = alt.Y("time",scale=alt.Scale(type='log'),title="log(total time)"),
)

alt.Chart(...)

In [10]:
overall = trial.groupby(["condition","nPts"]).sum().reset_index()
chart = alt.Chart(overall,title = "Overall").mark_bar().encode(
    x = "condition",
    y = alt.Y("time",scale=alt.Scale(type='log'),title="log(total time)"),
    column="nPts",
    color="condition",
    tooltip=["time"]
)
chart = chart.configure_title(fontSize=16, offset=5, orient='top', anchor='middle')
chart

alt.Chart(...)

In [12]:
overall = trial.groupby(["condition","nPts","cell_type"]).mean().reset_index()
pdf = overall[overall["cell_type"] =="python"]
chart = alt.Chart(pdf,title = "Non-Lux Python Operations").mark_bar().encode(
    x = "condition",
    y = alt.Y("time",scale=alt.Scale(type='log'),title="log(total time)"),
    column="nPts",
    color="condition"
)
chart = chart.configure_title(fontSize=16, offset=5, orient='top', anchor='middle')
chart

alt.Chart(...)

In [13]:
overall = trial.groupby(["condition","nPts","cell_type"]).mean().reset_index()
pdf = overall[overall["cell_type"] =="print_series"]
chart = alt.Chart(pdf,title = "Print Series").mark_bar().encode(
    x = "condition",
    y = alt.Y("time",scale=alt.Scale(type='log'),title="log(total time)"),
    column="nPts",
    color="condition",
    tooltip=["time"]
)
chart = chart.configure_title(fontSize=16, offset=5, orient='top', anchor='middle')
chart

alt.Chart(...)

In [14]:
overall = trial.groupby(["condition","nPts","cell_type"]).mean().reset_index()
pdf = overall[overall["cell_type"] =="print_dataframe"]
chart = alt.Chart(pdf,title = "Print Dataframe").mark_bar().encode(
    x = "condition",
    y = alt.Y("time",scale=alt.Scale(type='log'),title="log(total time)"),
    column="nPts",
    color="condition",
    tooltip=["time"]
)
chart = chart.configure_title(fontSize=16, offset=5, orient='top', anchor='middle')
chart

alt.Chart(...)

------------

### Communities post processing

In [65]:
count = []
with open("communities/communities.ipynb") as json_file:
    data = json.load(json_file)
    for cell in data['cells']:
        label = cell["source"][0]
        cell_type = None
        if "# {{NO LUX}}" in label:
            cell_type = "python"
        elif "# {{PRINT SERIES}}" in label:
            cell_type = "print_series"
        elif "# {{PRINT DF}}" in label:
            cell_type = "print_dataframe"
        count.append(cell_type)
count = pd.Series(count)
print(count.value_counts())

python             30
print_dataframe    14
print_series        4
dtype: int64


In [66]:
import glob
import time
import papermill as pm
import pandas as pd
import numpy as np
import json
trial = []

for nb_name in glob.glob("communities/communities_*_output.ipynb"):
# for nb_name in glob.glob("airbnb/airbnb_*_*_output.ipynb"):
    snb = nb_name.split("_")
    if len(snb)==4:
        _, condition, nPts, _ = nb_name.split("_")
    elif len(snb)==3:
        condition = "pandas"
        _,  nPts, _ = nb_name.split("_")
    with open(nb_name) as json_file:
        data = json.load(json_file)
        for cell in data['cells']:
            label = cell["source"][0]
            cell_type = None
            if "# {{NO LUX}}" in label:
                cell_type = "python"
            elif "# {{PRINT SERIES}}" in label:
                cell_type = "print_series"
            elif "# {{PRINT DF}}" in label:
                cell_type = "print_dataframe"
            duration = cell["metadata"]["papermill"]["duration"]
#             print(nb_name, cell_type, duration)
            trial.append([condition, nPts,cell_type, duration])

trial = pd.DataFrame(trial,columns=["condition","nPts","cell_type","time"])

In [67]:
trial.to_csv("../../paper/communities_macrobenchmark.csv",index=None)

In [22]:
overall = trial.groupby(["condition","nPts"]).sum().reset_index()
overall=overall[overall["time"]!=0]
chart = alt.Chart(overall,title = "Overall").mark_bar().encode(
    x = "condition",
    y = alt.Y("time",scale=alt.Scale(type='log'),title="log(total time)"),
    column="nPts",
    color="condition",
    tooltip=["time"]
)
chart = chart.configure_title(fontSize=16, offset=5, orient='top', anchor='middle')
chart

alt.Chart(...)

In [23]:
overall = trial.groupby(["condition","nPts","cell_type"]).mean().reset_index()
pdf = overall[overall["cell_type"] =="python"]
chart = alt.Chart(pdf,title = "Non-Lux Python Operations").mark_bar().encode(
    x = "condition",
    y = alt.Y("time",scale=alt.Scale(type='log'),title="log(total time)"),
    column="nPts",
    color="condition"
)
chart = chart.configure_title(fontSize=16, offset=5, orient='top', anchor='middle')
chart

alt.Chart(...)

In [24]:
overall = trial.groupby(["condition","nPts","cell_type"]).mean().reset_index()
pdf = overall[overall["cell_type"] =="print_series"]
chart = alt.Chart(pdf,title = "Print Series").mark_bar().encode(
    x = "condition",
    y = alt.Y("time",scale=alt.Scale(type='log'),title="log(total time)"),
    column="nPts",
    color="condition",
    tooltip=["time"]
)
chart = chart.configure_title(fontSize=16, offset=5, orient='top', anchor='middle')
chart.interactive()

alt.Chart(...)

In [25]:
overall = trial.groupby(["condition","nPts","cell_type"]).mean().reset_index()
pdf = overall[overall["cell_type"] =="print_dataframe"]
chart = alt.Chart(pdf,title = "Print Dataframe").mark_bar().encode(
    x = "condition",
    y = alt.Y("time",scale=alt.Scale(type='log'),title="log(total time)"),
    column="nPts",
    color="condition",
    tooltip=["time"]
)
chart = chart.configure_title(fontSize=16, offset=5, orient='top', anchor='middle')
chart

alt.Chart(...)

----------------

In [10]:
# # VegaLite can not do logarithmic stacked bar since it is misleading
# alt.Chart(df).mark_bar().encode(
#     x = alt.X("nPts",type="ordinal"),
#     y = alt.Y("time"),#,scale=alt.Scale(type='log'),title="log(total time)"),
#     color="condition"
# )

In [59]:
import numpy as np

In [73]:
def pctChange(s1,s2):
    return (np.array(s1["time"])-np.array(s2["time"]))/np.array(s2["time"])
def rawChange(s1,s2):
    return (np.array(s1["time"])-np.array(s2["time"]))

In [105]:
df = pd.read_csv("../../paper/airbnb_macrobenchmark.csv")

In [106]:
df = df[df["cell_type"]=="print_dataframe"]
df = df.groupby(["nPts","condition"]).mean().reset_index()

In [107]:
# df = df.groupby(["nPts","condition"]).sum().reset_index()
pdonly = df[df["condition"]=="pandas"]
best = df[df["condition"]=="o1o2o3"]
worst = df[df["condition"]=="baseline"]

In [108]:
pctChange(best,pdonly)

array([  6.7621107 ,  10.57342565,  55.34298331, 446.47839672])

In [109]:
pctChange(worst,pdonly)

array([  46.22273248,  102.25435485,  430.82242355, 3217.49196613])

In [110]:
pctChange(worst,best)

array([5.0837489 , 7.92167609, 6.66417393, 6.19250804])

In [111]:
rawChange(best,pdonly)

array([ 0.29964893,  0.46699271,  2.49405921, 23.73032679])

In [30]:
def singlePctChange(v1,v2):
    return (v1-v2)/v2

In [31]:
singlePctChange(7453,420.31)

16.732150079703075

In [112]:
df = pd.read_csv("../../paper/communities_macrobenchmark.csv")

In [113]:
df = df[df["cell_type"]=="print_dataframe"]
df = df.groupby(["nPts","condition"]).mean().reset_index()

In [114]:
# df = df.groupby(["nPts","condition"]).sum().reset_index()
pdonly = df[df["condition"]=="pandas"]
best = df[df["condition"]=="o1o2o3"]
worst = df[df["condition"]=="baseline"]

In [115]:
pctChange(best,pdonly)

array([13.93781355, 13.9749836 , 16.26765115, 10.17918056])

In [116]:
pctChange(worst,pdonly)

array([1359.19225188, 1390.9491227 , 6356.02771696, 4328.17054767])

In [117]:
pctChange(worst,best)

array([ 90.05698417,  91.95162921, 367.14663798, 386.25294098])

In [118]:
rawChange(best,pdonly)

array([0.96940779, 0.92198357, 1.06572171, 1.12403529])

In [133]:
df = pd.read_csv("../../paper/airbnb_macrobenchmark.csv")
df = df[df["cell_type"]=="python"]
df = df.groupby(["nPts","condition"]).mean().reset_index()

pdonly = df[df["condition"]=="pandas"]
o1 = df[df["condition"]=="o1"]
o1o2 = df[df["condition"]=="o1o2"]
best = df[df["condition"]=="o1o2o3"]
worst = df[df["condition"]=="baseline"]

# rawChange(best,pdonly)
# pctChange(worst,best)
pctChange(worst,o1)

array([  2.10172525,   4.5030616 ,  18.02373243, 107.99725214])

In [134]:
df = pd.read_csv("../../paper/communities_macrobenchmark.csv")
df = df[df["cell_type"]=="python"]
df = df.groupby(["nPts","condition"]).mean().reset_index()

pdonly = df[df["condition"]=="pandas"]
o1 = df[df["condition"]=="o1"]
o1o2 = df[df["condition"]=="o1o2"]
best = df[df["condition"]=="o1o2o3"]
worst = df[df["condition"]=="baseline"]

# rawChange(best,pdonly)
# pctChange(worst,best)
pctChange(worst,o1)

array([224.64270666, 190.06018366, 251.27066912,   4.3513446 ])