In [1]:
cd ../backend/macrobenchmark/

/Users/dorislee/Desktop/Research/lux/lux-benchmark/backend/macrobenchmark


In [2]:
import glob
import time
import papermill as pm
import pandas as pd
import numpy as np
import json
count = []
with open("airbnb/airbnb.ipynb") as json_file:
    data = json.load(json_file)
    for cell in data['cells']:
        label = cell["source"][0]
        cell_type = None
        if "# {{NO LUX}}" in label:
            cell_type = "python"
        elif "# {{PRINT SERIES}}" in label:
            cell_type = "print_series"
        elif "# {{PRINT DF}}" in label:
            cell_type = "print_dataframe"
        count.append(cell_type)
count = pd.Series(count)
print(count.value_counts())

python             17
print_dataframe    14
print_series        7
dtype: int64


In [3]:
trial = []

for nb_name in glob.glob("airbnb/airbnb_*_output.ipynb"):
# for nb_name in glob.glob("airbnb/airbnb_*_*_output.ipynb"):
    snb = nb_name.split("_")
    if len(snb)==4:
        _, condition, nPts, _ = nb_name.split("_")
    elif len(snb)==3:
        condition = "pandas"
        _,  nPts, _ = nb_name.split("_")
    with open(nb_name) as json_file:
        data = json.load(json_file)
        for cell in data['cells']:
            label = cell["source"][0]
            cell_type = None
            if "# {{NO LUX}}" in label:
                cell_type = "python"
            elif "# {{PRINT SERIES}}" in label:
                cell_type = "print_series"
            elif "# {{PRINT DF}}" in label:
                cell_type = "print_dataframe"
            duration = cell["metadata"]["papermill"]["duration"]
            trial.append([condition, nPts,cell_type, duration])
#             from datetime import datetime
#             if ("execution" in cell["metadata"]):
#                 starttime = datetime.strptime(cell["metadata"]["execution"]["iopub.execute_input"],"%Y-%m-%dT%H:%M:%S.%fZ")
#                 endtime = datetime.strptime(cell["metadata"]["execution"]["shell.execute_reply"],"%Y-%m-%dT%H:%M:%S.%fZ")
#                 duration = (endtime-starttime).total_seconds()
#     #             print(nb_name, cell_type, duration)
#                 trial.append([condition, nPts,cell_type, duration])
# #             else:
#                 print ("skip:",cell)

In [4]:
trial = pd.DataFrame(trial,columns=["condition","nPts","cell_type","time"])

In [5]:
trial=trial[trial["time"]!=0]

In [6]:
trial.to_csv("../../paper/airbnb_macrobenchmark.csv",index=None)

In [7]:
# trial.groupby("cell_type").count()

--------------

In [8]:
import pandas as pd
import altair as alt

In [9]:
overall = trial.groupby("condition").sum().reset_index()

In [10]:
alt.Chart(overall).mark_bar().encode(
    x = "condition",
    y = alt.Y("time",scale=alt.Scale(type='log'),title="log(total time)"),
)

alt.Chart(...)

In [11]:
overall = trial.groupby(["condition","nPts"]).sum().reset_index()

In [12]:
overall=overall[overall["time"]!=0]

In [13]:
chart = alt.Chart(overall,title = "Overall").mark_bar().encode(
    x = "condition",
    y = alt.Y("time",scale=alt.Scale(type='log'),title="log(total time)"),
    column="nPts",
    color="condition",
    tooltip=["time"]
)
chart = chart.configure_title(fontSize=16, offset=5, orient='top', anchor='middle')
chart

alt.Chart(...)

In [14]:
overall = trial.groupby(["condition","nPts","cell_type"]).mean().reset_index()
pdf = overall[overall["cell_type"] =="python"]
chart = alt.Chart(pdf,title = "Non-Lux Python Operations").mark_bar().encode(
    x = "condition",
    y = alt.Y("time",scale=alt.Scale(type='log'),title="log(total time)"),
    column="nPts",
    color="condition"
)
chart = chart.configure_title(fontSize=16, offset=5, orient='top', anchor='middle')
chart

alt.Chart(...)

In [15]:
overall = trial.groupby(["condition","nPts","cell_type"]).mean().reset_index()
pdf = overall[overall["cell_type"] =="print_series"]
chart = alt.Chart(pdf,title = "Print Series").mark_bar().encode(
    x = "condition",
    y = alt.Y("time",scale=alt.Scale(type='log'),title="log(total time)"),
    column="nPts",
    color="condition",
    tooltip=["time"]
)
chart = chart.configure_title(fontSize=16, offset=5, orient='top', anchor='middle')
chart

alt.Chart(...)

In [16]:
overall = trial.groupby(["condition","nPts","cell_type"]).mean().reset_index()
pdf = overall[overall["cell_type"] =="print_dataframe"]
chart = alt.Chart(pdf,title = "Print Dataframe").mark_bar().encode(
    x = "condition",
    y = alt.Y("time",scale=alt.Scale(type='log'),title="log(total time)"),
    column="nPts",
    color="condition",
    tooltip=["time"]
)
chart = chart.configure_title(fontSize=16, offset=5, orient='top', anchor='middle')
chart

alt.Chart(...)

------------

### Communities post processing

In [17]:
count = []
with open("latest_final_30kcap/communities/communities.ipynb") as json_file:
    data = json.load(json_file)
    for cell in data['cells']:
        label = cell["source"][0]
        cell_type = None
        if "# {{NO LUX}}" in label:
            cell_type = "python"
        elif "# {{PRINT SERIES}}" in label:
            cell_type = "print_series"
        elif "# {{PRINT DF}}" in label:
            cell_type = "print_dataframe"
        count.append(cell_type)
count = pd.Series(count)
print(count.value_counts())

python             30
print_dataframe    14
print_series        4
dtype: int64


In [18]:
import glob
import time
import papermill as pm
import pandas as pd
import numpy as np
import json
trial = []

for nb_name in glob.glob("communities/communities_*_output.ipynb"):
# for nb_name in glob.glob("airbnb/airbnb_*_*_output.ipynb"):
    snb = nb_name.split("_")
    if len(snb)==4:
        _, condition, nPts, _ = nb_name.split("_")
    elif len(snb)==3:
        condition = "pandas"
        _,  nPts, _ = nb_name.split("_")
    with open(nb_name) as json_file:
        data = json.load(json_file)
        for cell in data['cells']:
            label = cell["source"][0]
            cell_type = None
            if "# {{NO LUX}}" in label:
                cell_type = "python"
            elif "# {{PRINT SERIES}}" in label:
                cell_type = "print_series"
            elif "# {{PRINT DF}}" in label:
                cell_type = "print_dataframe"
            duration = cell["metadata"]["papermill"]["duration"]
#             print(nb_name, cell_type, duration)
            trial.append([condition, nPts,cell_type, duration])
#             duration = cell["metadata"]["papermill"]["duration"]
#             from datetime import datetime
#             if ("execution" in cell["metadata"]):
#                 starttime = datetime.strptime(cell["metadata"]["execution"]["iopub.execute_input"],"%Y-%m-%dT%H:%M:%S.%fZ")
#                 endtime = datetime.strptime(cell["metadata"]["execution"]["shell.execute_reply"],"%Y-%m-%dT%H:%M:%S.%fZ")
#                 duration = (endtime-starttime).total_seconds()
#     #             print(nb_name, cell_type, duration)
#                 trial.append([condition, nPts,cell_type, duration])
# #             else:
#                 print ("skip:",cell)

trial = pd.DataFrame(trial,columns=["condition","nPts","cell_type","time"])

In [19]:
trial.to_csv("../../paper/communities_macrobenchmark.csv",index=None)

In [20]:
overall = trial.groupby(["condition","nPts"]).sum().reset_index()
overall=overall[overall["time"]!=0]
chart = alt.Chart(overall,title = "Overall").mark_bar().encode(
    x = "condition",
    y = alt.Y("time",scale=alt.Scale(type='log'),title="log(total time)"),
    column="nPts",
    color="condition",
    tooltip=["time"]
)
chart = chart.configure_title(fontSize=16, offset=5, orient='top', anchor='middle')
chart

alt.Chart(...)

In [21]:
overall = trial.groupby(["condition","nPts","cell_type"]).mean().reset_index()
pdf = overall[overall["cell_type"] =="python"]
chart = alt.Chart(pdf,title = "Non-Lux Python Operations").mark_bar().encode(
    x = "condition",
    y = alt.Y("time",scale=alt.Scale(type='log'),title="log(total time)"),
    column="nPts",
    color="condition",
    tooltip=["time"]
)
chart = chart.configure_title(fontSize=16, offset=5, orient='top', anchor='middle')
chart

alt.Chart(...)

In [22]:
overall = trial.groupby(["condition","nPts","cell_type"]).mean().reset_index()
pdf = overall[overall["cell_type"] =="print_series"]
chart = alt.Chart(pdf,title = "Print Series").mark_bar().encode(
    x = "condition",
    y = alt.Y("time",scale=alt.Scale(type='log'),title="log(total time)"),
    column="nPts",
    color="condition",
    tooltip=["time"]
)
chart = chart.configure_title(fontSize=16, offset=5, orient='top', anchor='middle')
chart.interactive()

alt.Chart(...)

In [23]:
# trial[(trial["cell_type"] =="print_series")&(trial["condition"] =="o1o2")&((trial["nPts"] =="10000")|(trial["nPts"] =="100000"))]

In [54]:
# trial[(trial["cell_type"] =="print_series")&(trial["condition"] =="o1o2")&((trial["nPts"] =="10000")|(trial["nPts"] =="100000"))]

There are only 4 print series cells, which means that there is high variance in the execution time. If we do a rerun of experiments, we should add in more series cells. Esp since the metadata is recomputed for some of the series cells. Otherwise, the runtime is more or less the same. If we use papermill's "duration" v.s. subtract "execution" time (IPython messaging statrt/end), we get different results. So the conditions are more or less the same, but require reruns for the numbers to stable down.

In [55]:
trial[(trial["cell_type"] =="print_dataframe")&(trial["condition"] =="o1o2")&(trial["nPts"] =="10000")]

condition   nPts        cell_type        time
114      o1o2  10000  print_dataframe  113.509745
116      o1o2  10000  print_dataframe  139.958483
121      o1o2  10000  print_dataframe  138.769197
123      o1o2  10000  print_dataframe    0.151162
125      o1o2  10000  print_dataframe    1.249980
127      o1o2  10000  print_dataframe    0.285488
130      o1o2  10000  print_dataframe  125.798173
133      o1o2  10000  print_dataframe  111.726947
134      o1o2  10000  print_dataframe    0.401725
136      o1o2  10000  print_dataframe   51.866253
137      o1o2  10000  print_dataframe   40.801248
141      o1o2  10000  print_dataframe   46.909456
143      o1o2  10000  print_dataframe   45.405020
149      o1o2  10000  print_dataframe    0.231727

In [24]:
overall = trial.groupby(["condition","nPts","cell_type"]).mean().reset_index()
pdf = overall[overall["cell_type"] =="print_dataframe"]
chart = alt.Chart(pdf,title = "Print Dataframe").mark_bar().encode(
    x = "condition",
    y = alt.Y("time",scale=alt.Scale(type='log'),title="log(total time)"),
    column="nPts",
    color="condition",
    tooltip=["time"]
)
chart = chart.configure_title(fontSize=16, offset=5, orient='top', anchor='middle')
chart

alt.Chart(...)

----------------

In [10]:
# # VegaLite can not do logarithmic stacked bar since it is misleading
# alt.Chart(df).mark_bar().encode(
#     x = alt.X("nPts",type="ordinal"),
#     y = alt.Y("time"),#,scale=alt.Scale(type='log'),title="log(total time)"),
#     color="condition"
# )

In [59]:
import numpy as np

In [15]:
def pctChange(s1,s2):
    return (np.array(s1["time"])-np.array(s2["time"]))/np.array(s2["time"])
def rawChange(s1,s2):
    return (np.array(s1["time"])-np.array(s2["time"]))

In [16]:
df = pd.read_csv("../../paper/airbnb_macrobenchmark.csv")

In [17]:
df = df[df["cell_type"]=="print_dataframe"]
df = df.groupby(["nPts","condition"]).mean().reset_index()

In [18]:
# df = df.groupby(["nPts","condition"]).sum().reset_index()
pdonly = df[df["condition"]=="pandas"]
best = df[df["condition"]=="o1o2o3"]
worst = df[df["condition"]=="baseline"]

In [24]:
# pctChange(best,pdonly)

# pctChange(worst,pdonly)

# pctChange(worst,best)
rawChange(best,pdonly)

array([ 0.15564243,  0.37043429,  1.99063757, 21.18188143])

When the dataframe contains fewer than 1M rows for Airbnb, each print incurs no more than 2 seconds for each print in addition to \pandas (in the 10M case, each print incurred an overhead of 21 seconds).

In [30]:
def singlePctChange(v1,v2):
    return (v1-v2)/v2

In [31]:
singlePctChange(7453,420.31)

16.732150079703075

In [112]:
df = pd.read_csv("../../paper/communities_macrobenchmark.csv")

In [113]:
df = df[df["cell_type"]=="print_dataframe"]
df = df.groupby(["nPts","condition"]).mean().reset_index()

In [114]:
pdonly = df[df["condition"]=="pandas"]
best = df[df["condition"]=="o1o2o3"]
worst = df[df["condition"]=="baseline"]

In [115]:
pctChange(best,pdonly)

array([13.93781355, 13.9749836 , 16.26765115, 10.17918056])

In [116]:
pctChange(worst,pdonly)

array([1359.19225188, 1390.9491227 , 6356.02771696, 4328.17054767])

In [117]:
pctChange(worst,best)

array([ 90.05698417,  91.95162921, 367.14663798, 386.25294098])

In [118]:
rawChange(best,pdonly)

array([0.96940779, 0.92198357, 1.06572171, 1.12403529])

 Likewise, for Communities, the overhead was no more than 1.2 seconds. 

In [133]:
df = pd.read_csv("../../paper/airbnb_macrobenchmark.csv")
df = df[df["cell_type"]=="python"]
df = df.groupby(["nPts","condition"]).mean().reset_index()

pdonly = df[df["condition"]=="pandas"]
o1 = df[df["condition"]=="o1"]
o1o2 = df[df["condition"]=="o1o2"]
best = df[df["condition"]=="o1o2o3"]
worst = df[df["condition"]=="baseline"]

# rawChange(best,pdonly)
# pctChange(worst,best)
pctChange(worst,o1)

array([  2.10172525,   4.5030616 ,  18.02373243, 107.99725214])

In [134]:
df = pd.read_csv("../../paper/communities_macrobenchmark.csv")
df = df[df["cell_type"]=="python"]
df = df.groupby(["nPts","condition"]).mean().reset_index()

pdonly = df[df["condition"]=="pandas"]
o1 = df[df["condition"]=="o1"]
o1o2 = df[df["condition"]=="o1o2"]
best = df[df["condition"]=="o1o2o3"]
worst = df[df["condition"]=="baseline"]

# rawChange(best,pdonly)
# pctChange(worst,best)
pctChange(worst,o1)

array([224.64270666, 190.06018366, 251.27066912,   4.3513446 ])